GeorgRinger\Autoswitchlistview\EventListener\ChangeBeViewEventListener:
  tags:
    - name: event.listener
      identifier: 'GeorgRinger\Autoswitchlistview\EventListener\ChangeBeViewEventListener'
      event: TYPO3\CMS\Backend\Controller\Event\ModifyPageLayoutContentEvent
